patchedDependencies:
  'quasar': patches/quasar.patch

overrides:
  '@types/node': '^26'
  'typescript': '^6'

allowBuilds:
  '@parcel/watcher': false
  '@sentry/cli': false
  'esbuild': false
  'sharp': false
