import { SECONDARY, Secondary } from './ItemBonusId'

// https://warcraft.wiki.gg/wiki/ItemLink
export const ITEM_MODIFIER_KEY = {
    TRANSMOG_APPEARANCE_ALL_SPECS: 0,
    TRANSMOG_APPEARANCE_SPEC_1: 1,
    UPGRADE_ID: 2,
    BATTLE_PET_SPECIES_ID: 3,
    BATTLE_PET_BREED_DATA: 4,
    BATTLE_PET_LEVEL: 5,
    BATTLE_PET_DISPLAY_ID: 6,
    ENCHANT_ILLUSION_ALL_SPECS: 7,
    ARTIFACT_APPEARANCE_ID: 8,
    TIMEWALKER_LEVEL: 9,
    ENCHANT_ILLUSION_SPEC_1: 10,
    TRANSMOG_APPEARANCE_SPEC_2: 11,
    ENCHANT_ILLUSION_SPEC_2: 12,
    TRANSMOG_APPEARANCE_SPEC_3: 13,
    ENCHANT_ILLUSION_SPEC_3: 14,
    TRANSMOG_APPEARANCE_SPEC_4: 15,
    ENCHANT_ILLUSION_SPEC_4: 16,
    CHALLENGE_MAP_CHALLENGE_MODE_ID: 17,
    CHALLENGE_KEYSTONE_LEVEL: 18,
    CHALLENGE_KEYSTONE_AFFIX_ID_1: 19,
    CHALLENGE_KEYSTONE_AFFIX_ID_2: 20,
    CHALLENGE_KEYSTONE_AFFIX_ID_3: 21,
    CHALLENGE_KEYSTONE_AFFIX_ID_4: 22,
    ARTIFACT_KNOWLEDGE_LEVEL: 23,
    ARTIFACT_TIER: 24,
    TRANSMOG_APPEARANCE_SPEC_5: 25,
    PVP_RATING: 26,
    ENCHANT_ILLUSION_SPEC_5: 27,
    CONTENT_TUNING_ID: 28,
    CHANGE_MODIFIED_CRAFTING_STAT_1: 29,
    CHANGE_MODIFIED_CRAFTING_STAT_2: 30,
    TRANSMOG_SECONDARY_APPEARANCE_ALL_SPECS: 31,
    TRANSMOG_SECONDARY_APPEARANCE_SPEC_1: 32,
    TRANSMOG_SECONDARY_APPEARANCE_SPEC_2: 33,
    TRANSMOG_SECONDARY_APPEARANCE_SPEC_3: 34,
    TRANSMOG_SECONDARY_APPEARANCE_SPEC_4: 35,
    TRANSMOG_SECONDARY_APPEARANCE_SPEC_5: 36,
    SOULBIND_CONDUIT_RANK: 37,
    ITEM_MODIFIER_CRAFTING_QUALITY_ID: 38,
    ITEM_MODIFIER_CRAFTING_SKILL_LINE_ABILITY_ID: 39,
    ITEM_MODIFIER_CRAFTING_DATA_ID: 40,
    ITEM_MODIFIER_CRAFTING_SKILL_REAGENTS: 41,
    ITEM_MODIFIER_CRAFTING_SKILL_WATERMARK: 42,
    ITEM_MODIFIER_CRAFTING_REAGENT_SLOT_0: 43,
    ITEM_MODIFIER_CRAFTING_REAGENT_SLOT_1: 44,
    ITEM_MODIFIER_CRAFTING_REAGENT_SLOT_2: 45,
    ITEM_MODIFIER_CRAFTING_REAGENT_SLOT_3: 46,
    ITEM_MODIFIER_CRAFTING_REAGENT_SLOT_4: 47,
    ITEM_MODIFIER_CRAFTING_REAGENT_SLOT_5: 48,
    ITEM_MODIFIER_CRAFTING_REAGENT_SLOT_6: 49,
    ITEM_MODIFIER_CRAFTING_REAGENT_SLOT_7: 50,
    ITEM_MODIFIER_CRAFTING_REAGENT_SLOT_8: 51,
    ITEM_MODIFIER_CRAFTING_REAGENT_SLOT_9: 52,
    ITEM_MODIFIER_CRAFTING_REAGENT_SLOT_10: 53,
    ITEM_MODIFIER_CRAFTING_REAGENT_SLOT_11: 54,
    ITEM_MODIFIER_CRAFTING_REAGENT_SLOT_12: 55,
    ITEM_MODIFIER_CRAFTING_REAGENT_SLOT_13: 56,
    ITEM_MODIFIER_CRAFTING_REAGENT_SLOT_14: 57,
    ITEM_MODIFIER_REFORGE: 58,
} as const

// Only applicable to CHANGE_MODIFIED_CRAFTING_STAT_1 and CHANGE_MODIFIED_CRAFTING_STAT_2
export const ITEM_MODIFIER_SECONDARY_VALUE = {
    CRIT: 32,
    HASTE: 36,
    MASTERY: 49,
    VERS: 40,
} as const

export type ItemModifierKey = (typeof ITEM_MODIFIER_KEY)[keyof typeof ITEM_MODIFIER_KEY]
export type ItemModifierSecondaryValue = (typeof ITEM_MODIFIER_SECONDARY_VALUE)[keyof typeof ITEM_MODIFIER_SECONDARY_VALUE]

export type ItemModifier = {
    type: ItemModifierKey
    value: number
}

export function getSecondaryFromModifiers(modifiers?: Array<ItemModifier>): Array<Secondary> | undefined {
    const secondaries = new Array<Secondary>()

    for (const modifier of modifiers ?? []) {
        if (modifier.type === ITEM_MODIFIER_KEY.CHANGE_MODIFIED_CRAFTING_STAT_1 || modifier.type === ITEM_MODIFIER_KEY.CHANGE_MODIFIED_CRAFTING_STAT_2) {
            switch (modifier.value) {
                case ITEM_MODIFIER_SECONDARY_VALUE.CRIT: {
                    secondaries.push(SECONDARY.CRIT)
                    break
                }
                case ITEM_MODIFIER_SECONDARY_VALUE.HASTE: {
                    secondaries.push(SECONDARY.HASTE)
                    break
                }
                case ITEM_MODIFIER_SECONDARY_VALUE.MASTERY: {
                    secondaries.push(SECONDARY.MASTERY)
                    break
                }
                case ITEM_MODIFIER_SECONDARY_VALUE.VERS: {
                    secondaries.push(SECONDARY.VERS)
                    break
                }
            }
        }
    }

    return secondaries.length === 0
        ? undefined
        : secondaries
}
