name: Continuous Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - README.md
      - .vscode
      - .editorconfig
      - .gitignore

env:
  WEB_IMAGE: ghcr.io/trinovantes/wowpay2win-web
  CRON_IMAGE: ghcr.io/trinovantes/wowpay2win-cron

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Save yarn cache location to env
        run: echo "YARN_CACHE=$(yarn cache dir)" >> $GITHUB_ENV

      - name: Cache node_modules
        uses: actions/cache@v2
        env:
          CACHE_NAME: cache-node-modules
        with:
          path: ${{ env.YARN_CACHE }}
          key: ${{ runner.os }}-build-${{ env.CACHE_NAME }}-${{ hashFiles('**/yarn.lock', '**/package-lock.json') }}

      - name: Install dependencies
        run: yarn install

      - name: Run linter
        run: yarn lint

  build:
    needs: test
    name: Build
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create .env file
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pull images from registry
        run: make pull || true

      - name: Build images
        run: make build

      - name: Push images to registry
        run: make push

      - name: Copy dist from image to disk for sentry upload
        run: |
          mkdir -p ./dist/cron
          TEMP_CONTAINER=$(docker create ${{ env.CRON_IMAGE }})
          docker cp $TEMP_CONTAINER:/app/dist/cron/. ./dist/cron
          docker rm $TEMP_CONTAINER

          mkdir -p ./dist/web
          TEMP_CONTAINER=$(docker create ${{ env.WEB_IMAGE }})
          docker cp $TEMP_CONTAINER:/app/dist/web/. ./dist/web
          docker rm $TEMP_CONTAINER

      - name: Create sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: production
          sourcemaps: ./dist/web ./dist/cron
          url_prefix: ~/

  deploy:
    needs: build
    name: Deploy
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create .env file
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Create SSH key to production
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "${{ secrets.SSH_KEYSCAN }}" > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Create and use remote context
        run: |
          docker context create remote --docker "host=ssh://${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}"
          docker context use remote

      - name: Pull images from registry
        run: make pull

      - name: Start containers
        run: make run

      - name: Prune old images
        run: docker image prune -f
